export const exportLabels = {
  en: {
    cv: "Curriculum Vitae",
    summary: "Profile Summary",
    experience: "Work Experience",
    education: "Education",
    skills: "Skills",
    languages: "Languages",
    certifications: "Certifications",
    hobbies: "Hobbies",
    contact: "Contact Information",
    references: "References available upon request",
    fullName: "Full Name",
    jobTitle: "Job Title",
    dateOfBirth: "Date of Birth",
    nationality: "Nationality",
    gender: "Gender",
    photo: "Photo",
    phone: "Phone",
    email: "Email",
    address: "Address",
    linkedin: "LinkedIn",
    website: "Website",
    projects: "Projects",
    awards: "Awards",
    publications: "Publications"
  },
  fr: {
    cv: "Curriculum Vitae",
    summary: "Résumé du Profil",
    experience: "Expérience Professionnelle",
    education: "Éducation",
    skills: "Compétences",
    languages: "Langues",
    certifications: "Certifications",
    hobbies: "Loisirs",
    contact: "Informations de Contact",
    references: "Références disponibles sur demande",
    fullName: "Nom Complet",
    jobTitle: "Intitulé du poste",
    dateOfBirth: "Date de naissance",
    nationality: "Nationalité",
    gender: "Sexe",
    photo: "Photo",
    phone: "Téléphone",
    email: "Courriel",
    address: "Adresse",
    linkedin: "LinkedIn",
    website: "Site Web",
    projects: "Projets",
    awards: "Récompenses",
    publications: "Publications"
  },
  ar: {
    cv: "السيرة الذاتية",
    summary: "نبذة شخصية",
    experience: "الخبرة العملية",
    education: "التعليم",
    skills: "المهارات",
    languages: "اللغات",
    certifications: "الشهادات",
    hobbies: "الهوايات",
    contact: "معلومات الاتصال",
    references: "المراجع متاحة عند الطلب",
    fullName: "الاسم الكامل",
    jobTitle: "المسمى الوظيفي",
    dateOfBirth: "تاريخ الميلاد",
    nationality: "الجنسية",
    gender: "الجنس",
    photo: "الصورة",
    phone: "الهاتف",
    email: "البريد الإلكتروني",
    address: "العنوان",
    linkedin: "لينكدإن",
    website: "الموقع الإلكتروني",
    projects: "المشاريع",
    awards: "الجوائز",
    publications: "المنشورات"
  }
};